DROP TABLE IF EXISTS users, recipes, cart;


-- userid is auth0 id
CREATE TABLE users (
    id SERIAL PRIMARY KEY ,
    userid text, 
    displayName TEXT
);

INSERT INTO users (userid, displayName)
VALUES ('1', 'ashTest');


CREATE TABLE recipes (
    id SERIAL PRIMARY KEY,
    Price DECIMAL,
    Name TEXT,
    ImageFull TEXT,
    Thumbnail TEXT,
    Description TEXT,
    Servings INTEGER,
    Calories INTEGER,
    Fat INTEGER,
    Carbs INTEGER,
    Protein INTEGER
);

INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Beet Burger with Roasted Grapes & Herb Garlic Cashew Cheese', 'https://s3-us-west-2.amazonaws.com/purplecarrot/beet-burger-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/beet-burger-thumbnail.jpg', 'Vegetable based burgers are all the rage right now, and we want you to be able to create your own at home. Earthy red beets are the base, and can be shredded by hand or pulsed in a food processor (that’s the way we like to do it) to achieve the proper consistency. Toppings include herb garlic cashew based cheese and roasted red grapes. Be sure to taste one of the grapes as they come out of the oven– it might become your new favorite snack!', 2, 850, 39, 95, 31);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Curried Millet with Asparagus & Apricot Onion Chutney', 'https://s3-us-west-2.amazonaws.com/purplecarrot/curried-millet-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/curried-millet-thumbnail.jpg', 'Millet is a gluten free ancient grain, widely known around the world for its mild flavor, versatility, and nutritional benefits. This aromatic curried millet is the perfect base for crunchy shiitake mushrooms and tender asparagus, which get kicked up with hazelnuts toasted to perfection in the skillet. The chutney comes together in mere minutes, and the recipe can be used again with any type of preserve as the base– we suggest trying rhubarb next!', 2, 650, 30, 83, 14);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Seitan Massaman Curry with Blistered Cherry Tomatoes and Brown Basmati Rice', 'https://s3-us-west-2.amazonaws.com/purplecarrot/seitan-curry-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/seitan-curry-thumbnail.jpg', 'Massaman is a staple in many Thai restaurants, but the history can be traced back to the Middle East. The tangy tamarind base of the curry gets rounded out with warm aromatic spices like cardamom, cinnamon, and cloves. We sear the seitan before it gets tossed in the sauce so that it stays crisp, so don’t be afraid to let it get nice and browned in the skillet. Adjust the heat as you go and shake the skillet frequently for best results.', 2, 870, 37, 76, 52);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Seitan Gyro with Shaved Artichoke Salad and Tahini Yogurt', 'https://s3-us-west-2.amazonaws.com/purplecarrot/seitan-gyro-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/seitan-gyro-thumbnail.jpg', 'One of the best parts about a gyro is the combination of flavors and textures. Crispy seitan, dusted with baharat spice, is paired with crunchy cucumber and a smooth vegan tahini yogurt sauce. Baharat spice is a traditional Middle Eastern blend with allspice, cloves, and cumin. It brings an authentic, warm flavor to the dish but use as little or as much as you’d like depending on your affinity to spice. Wrap everything up in warm pita and enjoy!', 2, 570, 24, 47, 39);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Elote Bowl with Lime Chickpeas and Quinoa', 'https://s3-us-west-2.amazonaws.com/purplecarrot/elote-bowl-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/elote-bowl-thumbnail.jpg', 'Elote is the Spanish word for corn, and this sweet summer vegetable is the highlight of our “street corn” bowl. Mexican style corn is usually grilled, so fire it up if you have one. Instead of cutting the corn kernels from the cob, lay them whole on a hot grill and cook until charred, it should only take a few minutes. The key to crispy chickpeas is not shaking the pan too often, they should be brown in places and smell a bit toasted.', 2, 740, 28, 105, 27);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Kale Caesar with Crispy Butter Beans and Everything "Bagel" Croutons', 'https://s3-us-west-2.amazonaws.com/purplecarrot/kale-ceasar-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/kale-ceasar-thumbnail.jpg', 'Fun fact: Caesar Cardini, an Italian immigrant, is credited with inventing the Caesar salad in the 1920’s. Usually dressed with a combination of cheese, anchovies, egg, and oil, our kale Caesar takes a lighter approach, bumping up the flavor with briny capers, tahini, and dijon mustard. We also sub out run-of-the-mill croutons for “everything bagel” croutons. You’ll have trouble not eating them right off the baking sheet!', 2, 460, 16, 64, 20);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Strawberry Cherry Tomato Gazpacho with Avocado Toast & Balsamic Reduction', 'https://s3-us-west-2.amazonaws.com/purplecarrot/gazpacho-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/gazpacho-thumbnail.jpg', 'Avocado toast has made it into the headlines lately but we think it should be there all the time. What’s better than a buttery fruit (yes, avocado is a fruit) that pairs perfectly with crunchy toast? This chilled summer soup can be made in a food processor or a blender and be sure to taste and season with salt as you go. If you have time, wipe the strawberries with a damp paper towel instead of rinsing, it will keep them from absorbing water.', 2, 470, 18, 68, 12);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Portobello Steaks with Tomato Orzo Salad & Chimichurri', 'https://s3-us-west-2.amazonaws.com/purplecarrot/portobello-steaks-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/portobello-steaks-thumbnail.jpg', 'The best trick to trim asparagus is to hold the ends of a spear with both hands and find the natural snapping point towards the bottom of the stalk. Line them up and cut the entire bunch at this point, discarding the woody ends. The roasted vegetables get mixed into a tomato orzo and everything gets topped with herby, citrusy chimichurri, a South American sauce known for its bright color and bold flavor– it’s one of our all time favorites.', 2, 540, 24, 70, 15);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Eggplant Parmesan Flatbread with Shaved Zucchini and Arugula Salad', 'https://s3-us-west-2.amazonaws.com/purplecarrot/eggplant-flatbread-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/eggplant-flatbread-thumbnail.jpg', 'Mozzarella and sundried tomatoes make the dish taste like an authentic eggplant parmesan. A mandoline may be the most cost effective tool to have in your kitchen: it can help in a variety of instances from making fries to thinly slicing vegetables for a salad. If you have a grill, this is a good dish to fire it up for. The eggplant can be grilled and after the flatbreads are assembled, simply leave them on the grill for a few moments with the lid closed to melt the cheese.', 2, 770, 41, 85, 16);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Tempeh Tacos Al Pastor with Pineapple Salsa', 'https://s3-us-west-2.amazonaws.com/purplecarrot/tempeh-tacos-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/tempeh-tacos-thumbnail.jpg', 'Dried chiles are packed with concentrated flavors such as smoke and spice. Here we use a guajillo chile, a Mexican pepper that is a relatively low heat compared to the flavor it packs. We recommend that you warm your tortillas however you see fit. Don’t feel like turning on the oven? Toss them on the grill, on an open stovetop flame for a moment, or even in the microwave, covered with a damp paper towel.', 2, 710, 25, 93, 29);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Carrot Socca with Red Lettuce Blackberry Salad and Dill Dressing', 'https://s3-us-west-2.amazonaws.com/purplecarrot/carrot-socca-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/carrot-socca-thumbnail.jpg', 'Sweet shredded carrots get folded into a high protein batter before getting pan fried into tender socca cakes. Leave the peels on the carrots, they hold extra fiber and nutrients. Be sure to use a nonstick pan since the carrots are high in natural sugars and could burn easily. The juicy blackberries get tossed into the salad last and pair nicely with the zingy vinaigrette.', 2, 530, 34, 47, 14);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Watermelon Poke Bowl with Macadamia Nuts & Sea Lettuce Dressing', 'https://s3-us-west-2.amazonaws.com/purplecarrot/watermelon-poke-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/watermelon-poke-thumbnail.jpg', 'The Hawaiian “poke bowl” brings together the sea, the land, and all the diverse flavors that go along with. In our version, watermelon radish and macadamia nuts provide the earthy crunch while the savory sea lettuce, or seaweed flakes, provide the sea factor. This is a quick meal, so as soon as the rice is finished uncover it and allow it to cool a bit before building your delicious bowl.', 2, 520, 23, 77, 11);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Empanadas with Black Bean Puree and Jicama-Corn Salad', 'https://s3-us-west-2.amazonaws.com/purplecarrot/empanada-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/empanada-thumbnail.jpg', 'Black beans, lime, and corn are always a good combination and it’s especially true when the black beans are smooth and creamy and the corn is seasoned with fresh cilantro and lime. Here we take half of the beans and blend them with vegan sour cream; if they get a bit dry just add an extra tablespoon of water as necessary. Since the empanadas are baked, not fried, if all of the corners aren’t sealed perfectly they’ll still be delicious.', 2, 890, 33, 141, 34);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Wicked Healthy Kitchari with Minted Cucumber Avocado Salad & Toasted Naan', 'https://s3-us-west-2.amazonaws.com/purplecarrot/kitchari-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/kitchari-thumbnail.jpg', 'This meal comes from our friends at Wicked Healthy and it’s a one pot wonder that builds flavor at every step. With a dish like this, it’s important to taste and season often– doesn’t sound too bad does it? The tarka, which is a toasted spice paste, includes mustard seeds, coriander, and cumin, and we toast it to bring out all of the aromatic goodness. If you’d prefer not to turn on the oven for the naan, try popping it in the toaster to warm.', 2, 760, 19, 117, 25);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Maple Tempeh with Lime Couscous Salad and Minty Plums', 'https://s3-us-west-2.amazonaws.com/purplecarrot/maple-tempeh-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/maple-tempeh-thumbnail.jpg', 'The flavors in this dish may seem adventurous to some, with sweet maple, fresh lime, and bright mint, but we can assure you that they come together for a delicious finish. The tempeh gets a sweet and savory marinade before crisping up in a skillet. Be sure to keep an eye on the tempeh, the sugars could caramelize quickly- they’re ready when there’s a golden brown coating on each piece. The lime couscous is seriously flavorful, and if you love lime, add a little of the zest to the salad- we won’t tell.', 2, 840, 36, 100, 35);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein) 
VALUES (13.27, 'Thrive Sweet Pepper and Hemp Seed Pesto Pizza with Broccoli and Basil', 'https://s3-us-west-2.amazonaws.com/purplecarrot/hemp-pizza-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/hemp-pizza-thumbnail.jpg', 'Fresh broccoli and basil come together to create the perfect topping for a crispy mung bean pizza crust. The pesto recipe comes from professional Ironman triathlete Brendan Brazier’s Thrive Energy cookbook — it’ll have you praising the power of green! Along with red peppers and hemp seeds, you’ll love this flatbread-style pizza for its hearty flavors and health-boosting benefits.', 2, 700, 26, 85, 37);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Greek Salad with Za’atar Eggplant and Marinated “Feta”', 'https://s3-us-west-2.amazonaws.com/purplecarrot/greek-salad-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/greek-salad-thumbnail.jpg', 'Almond-based “feta” is the highlight of this meal with bright lemon zest, fresh thyme leaves, and olive oil that bring it all together. The salad itself is more of a hearty vegetable bowl with crunchy peppers, briny olives, and protein packed walnuts over a bed of romaine. If you have a grill, the eggplant can be sliced into ½ inch thick planks and drizzled with olive oil and sprinkled with salt and pepper before getting grilled on high heat.', 2, 490, 44, 24, 9);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Creamy Mac n’ Cheese with Green Chiles and Garlic Broccoli', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mac-cheese-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mac-cheese-thumbnail.jpg', 'Creamy and decadent, no one will believe this mac n’ cheese has a plant-based sauce! This family friendly meal can be made with or without the green chiles, which are generally on the milder side and packed with flavor. Buttery breadcrumbs coat the top and be sure to watch these closely in the oven, it should only take a few minutes. The garlic broccoli is a head nod to a childhood favorite, and is cooked last minute and served bright green.', 2, 880, 27, 129, 40);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Lemon Miso Cavatelli with Skillet Roasted Eggplant & Walnut Breadcrumbs', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lemon-miso-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lemon-miso-full.jpg', 'We’re confident this creamy sauce, made with cashews, miso paste, and lemon, can stand up to any alfredo. The cavatelli shape is perfect for the dish, hiding little pockets of the rich sauce for each bite. Remember to save some of the pasta water to thin the sauce, it’s a classic Italian technique that can be used in almost any recipe. Toasty breadcrumbs add crunch, so don’t be afraid to toast them up really well– it will deepen the flavor.', 2, 870, 40, 114, 23);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Southern Spoonbread with Black Eyed Pea Tomato Gravy & Greens', 'https://s3-us-west-2.amazonaws.com/purplecarrot/spoonbread-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/spoonbread-full.jpg', 'Spoonbread is a moist cornmeal “bread” that is actually more like a savory pudding. You can use a cast iron pan if you have one for a great crust on the outside and an evenly cooked center. The creamy Southern style gravy is packed with tender black-eyed peas for protein and fiber. If you’re unsure if your spoonbread is ready, use a paring knife or toothpick to pierce the center, if it comes out clean then you’re ready for dinner.', 2, 710, 37, 80, 18);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Sweet Corn Risotto with Lemon Parmesan Broccolini & Chervil', 'https://s3-us-west-2.amazonaws.com/purplecarrot/corn-risotto-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/corn-risotto-full.jpg', 'Oven roasted vegetables are almost always the tastiest, so we’ve dusted the broccolini with vegan parmesan and lemon zest and let it crisp up that way. The creamy risotto is surprisingly easy, with hot water added just a little at a time to pull the starches from the grains of rice. If you’ve never made risotto before, this recipe will ensure you learn the tricks. If you add wine, a half cup of dry white wine before you add any water is perfect.', 2, 650, 23, 100, 15);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Tempura Sweet Potato Bao with Quick Peach Kimchi & Meyer Lemon Aioli', 'https://s3-us-west-2.amazonaws.com/purplecarrot/tempura-potato-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/tempura-potato-full.jpg', 'Light and crispy, tempura is known for being on the healthier side of fried. It’s important to get the batter correct, so if it looks too thick after you mix in the water (the orange color of the sweet potato should show through the batter), add an extra tablespoon of cold water. The meyer lemon will give the aioli a rounded lemon flavor, and peach will counterbalance the spice in the kimchi. Warm the buns in the microwave if you’d like them hot.', 2, 720, 42, 79, 10);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Miso Soba Noodles with Charred Shishito Peppers & Summer Beans', 'https://s3-us-west-2.amazonaws.com/purplecarrot/miso-soba-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/miso-soba-full.jpg', 'Rinse and dry all produce. If you''re making this on a hot summer’s night (or even if not) then you’re in for a treat. Pieces of tofu marinate in sweet miso while you prepare a flavorful dressing for the chilled soba noodles. Miso paste is used throughout the recipe, so be careful to measure out and add the correct amounts at each step. Shishito peppers can sometimes pack a punch of heat, but are usually mild, they''re topped here with salt and togarashi– a Japanese chile blend.', 2, 760, 30, 92, 33);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Cauliflower Steaks with Zucchini-Poblano Sauce & Pistachio Dukkah', 'https://s3-us-west-2.amazonaws.com/purplecarrot/cauliflower-steaks-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/cauliflower-steaks-full.jpg', 'An earthy, green sauce hides under a pile of basmati rice pilaf, speckled with golden raisins and lima beans. If you haven’t made a cauliflower “steak” before you’re in for a treat. The goal here is to get it crispy, so don’t be afraid to let it brown really well in the oven– an even coat of oil will help with the cooking. The pistachio dukkah, a traditional aromatic spice and nut blend, is complex with scents of nigella, ginger, allspice, and fenugreek.', 2, 650, 24, 94, 19);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Portobello Fajitas with Black Beans & Poblano Crema', 'https://s3-us-west-2.amazonaws.com/purplecarrot/fajitas-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/fajitas-full.jpg', 'Sizzling fajitas always remind us of summer, and these could be our favorite yet. Throughout this recipe we mention “charring” and that term means to gain some color on the vegetables– in this case, the poblano pepper. Blackening the skin gives a deeper flavor to the sauce and, if you have a gas stove you could heat the tortillas right on the open flame, adding a bit of char there as well instead of using the oven...delicious.', 2, 740, 20, 129, 36);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Pad See Ew with Summer Squash & Thai Basil', 'https://s3-us-west-2.amazonaws.com/purplecarrot/padsee-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/padsee-full.jpg', 'This Chinese influenced Thai dish has fans all over the world. The flat, broad noodles hold onto the sweet and tangy sauce and fresh Thai basil keep the dish feeling light. We encourage the use of a regular skillet here, this way you’ll get the authentic caramelization of the noodles– they may stick to the pan a bit but use a spatula to help loosen them. If you like an extra kick of heat, don’t deseed the chile and add all of it to the dish.', 2, 800, 22, 133, 21);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Stuffed Sweet Potatoes with Spicy Soyrizo Picadillo & Chayote Salsa', 'https://s3-us-west-2.amazonaws.com/purplecarrot/soyrizo-potato-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/soyrizo-potato-full.jpg', 'Picadillo is chopped up goodness with peppers, onions, and in this case soyrizo– a beloved vegan product made with the same spices as chorizo, packing a bold flavor. Keep your skillet hot while you cook it to get some color, it deepens the flavors even more. Chayote is related to melons and cucumbers, and you can cut the flesh off the pit by standing it upright and cutting downwards. It’s a refreshing compliment to the smokey picadillo.', 2, 660, 25, 94, 23);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Zucchini Corn Cakes with Roasted Haricot Vert & Lemon Basil Aioli', 'https://s3-us-west-2.amazonaws.com/purplecarrot/zucchini-cakes-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/zucchini-cakes-full.jpg', 'Cleaning leeks may seem like a cumbersome task, but we have a way to make it painless. Once sliced, drop them into a bowl of water and separate the rings with your hands– all of the grit will fall to the bottom of the bowl leaving you with clean leeks. A “flax egg” is simply flaxmeal and water, and once it sits for a moment it becomes a great binder, just like a real egg. Be sure your skillet is hot as you drop the batter in for extra crisp cakes.', 2, 640, 39, 68, 15);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES(13.27, 'Sweet Pea Flatbread with Truffled Fingerling Potatoes & Kite Hill Ricotta', 'https://s3-us-west-2.amazonaws.com/purplecarrot/pea-flatbread-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/pea-flatbread-full.jpg', 'Truffle oil brings a unique, earthy flavor to this loaded flatbread. If you have a mandoline, use it to thinly slice the potatoes to will create a crispier outcome. To simplify the cooking, add the coconut to the same baking sheet as the potatoes, just give them a little scoot over with a spatula and drop in the coconut flakes. The sweet pea puree can be blended until smooth or left a little chunky, it will be tasty whichever way you prefer.', 2, 700, 37, 78, 20);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Vegetable Chow Mein with Baby Leeks & Miso Mustard Sauce', 'https://s3-us-west-2.amazonaws.com/purplecarrot/chow-mein.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/chow-mein.jpg', 'Tender baby leeks roast until golden brown while a Chinese classic with a healthy twist simmers on the stovetop. These stir-fried noodles are tossed with crunchy green cabbage, bright snow peas, and sweet carrots creating a vibrant dish packed with nutrients. The miso mustard sauce slathered on the leeks is sweet and spicy, a take on hot mustard that would make any meal better. If you’re sensitive to spice, you may want to enjoy it on the side.', 2, 450, 16, 68, 11);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Persian Stuffed Peppers with Creamy Lentils & Toasted Pistachios', 'https://s3-us-west-2.amazonaws.com/purplecarrot/stuffed-peppers-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/stuffed-peppers-full.jpg', 'Aromatic Persian rice is tucked into bright yellow peppers for an a eye-popping dinner. Rich scents of cumin, cardamom, and cinnamon will fill your kitchen as you spice the stuffing. Sour cherries dot the basmati rice with a chewy sweetness that Persian food is known, and loved for. Watch the pistachios carefully as they toast in the skillet, you want them lightly browned for a beautiful garnish at the end!', 2, 780, 30, 114, 27);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Zucchini Lasagna with Tofu Ricotta & Basil Panko', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lasagna-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lasagna-full.jpg', 'A childhood favorite gets a healthified makeover this week. Zucchini “noodles” and tofu “ricotta” are the two plant-based alterations that set this lasagna apart! Homemade red sauce gets its familiar flavors from garlic, shallot, and oregano. And finally, a panko topping adds much-needed crunch. Pro tip: our chefs recommend using a cast iron skillet if you have one!', 2, 450, 21, 46, 26);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Miso-Chili Meatballs with Broccoli Rabe & Mustard-Plum Sauce', 'https://s3-us-west-2.amazonaws.com/purplecarrot/miso-meatballs-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/miso-meatballs-full.jpg', 'These nutty, protein-rich “meatballs” are packed with complex flavor, thanks to the sweet and savory trio of red miso, plum sauce, and hot mustard. An additional layer of complexity comes from spicy sambal, a chili paste that is popular across Southeast Asia. Tender spelt berries top the dish, instead of going under the meatballs, which allow them to shine. To finish it off, slightly bitter broccoli rabe adds potassium, iron, calcium, fiber, and vitamins!', 2, 670, 37, 74, 19);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Red Lentil Ragu with Garden Vegetables & Whole Grain Angel Hair Pasta', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lentil-ragu-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lentil-ragu-full.jpg', 'Fennel, asparagus, and cherry tomatoes roast to perfection while you finish a hearty ragu of red lentils and tomatoes on the stovetop. Red lentils are packed with protein, and are best eaten tender but with the slightest bite– so while you’re making the ragu, check periodically to see when they’re ready. Fresh parsley lightens the dish in a simple vinaigrette. Serve any extra dressing on the side after you toss the roasted vegetables.', 2, 640, 17, 106, 26);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Vegetable Pad Thai with Sweet and Sour Tamarind & Vegan Egg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/pad-thai-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/pad-thai-full.jpg', 'Our solution to take out cravings? Healthy alternatives that don’t compromise on taste! In this dish we’ve combined sweet and sour tamarind with a rainbow of vegetables to boost the nutritional power. The addition of the vegan egg is what makes the meal reminiscent of your favorite Thai meal. Scramble it up, toss with the noodles, and top with fresh herbs and peanuts!', 2, 650, 17, 114, 14);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Korean Lettuce Wraps with Seitan and Ssam Sauce', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lettuce-wraps-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/lettuce-wraps-full.jpg', 'If you’re a fan of sweet and spicy Korean barbecue then you’re in for a treat. Tangy red miso and gochujang Ssam is balanced out with a sweet and cool cucumber sauce. The protein in this dish comes from seitan, which is also high in essential amino acids and iron. All of these flavors, along with hearty brown rice, come together wrapped up in a neat lettuce package.', 2, 680, 19, 83, 39);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Mustard Glazed Tempeh with Red Kraut and Smashed Beets', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mustard-tempeh-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mustard-tempeh-full.jpg', 'Golden beets and potatoes join together to create a hearty accompaniment to this mustard glazed tempeh. In addition, a side of sauerkraut offers a boost to your digestive health. It’s no surprise that fermented foods are all the rage among health enthusiasts these days, as they’re full of probiotics and enzymes! Here’s a hint to simplify the cooking process: if you find the tempeh difficult to cut into 8 pieces, 4 triangles will work fine!', 2, 600, 33, 49, 27);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Spring Radish Fattoush with Sumac Vinaigrette & Minted Basmati Rice', 'https://s3-us-west-2.amazonaws.com/purplecarrot/radish-fattoush-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/radish-fattoush-full.jpg', 'Commonly found in Middle Eastern cuisine, Fattoush is made with crisped pita bread, mixed greens, and a variety of veggies. Our recipe incorporates easter egg radishes, known for their vibrant pink and purple coloring. Dried mint and sumac give the vinaigrette dressing a refreshing, fruity taste, and bring out the flavor in the rice, which can be eaten on the side or mixed in with the salad!', 2, 500, 23, 72, 12);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Greek Braised Artichoke Hearts over Toasted Farro', 'https://s3-us-west-2.amazonaws.com/purplecarrot/artichoke-hearts-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/artichoke-hearts-full.jpg', 'Braised artichoke hearts are simmered with cinnamon and thyme to pick up flavor. They perch on top of a nest of toasted farro along with onion and bold Kalamata olives. Together they compose a bright stew that ties together all the different elements of this meal. With a sprinkle of your choice of Aromasong salt, this grain bowl has it all!', 2, 500, 19, 75, 14);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Sushi-rito with Sesame Aioli and Snap Pea Salad', 'https://s3-us-west-2.amazonaws.com/purplecarrot/sushi-rito-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/sushi-rito-full.jpg', 'If you have yet to experience the trendy creation known as the Sushi Burrito, we’ve got you covered. Rice and veggies come together in a rolled nori package, with a refreshing salad on the side. If you’d rather enjoy this meal in a more traditional manner, feel free to slice your Sushi-rito like a classic sushi roll. Or, for a deconstructed spin, build a sushi bowl lined with rice, layer with veggies, and top with crumbled nori!', 2, 560, 28, 71, 10);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Creamy Corn & Fennel Chowdah with Dilly Garlic Bread', 'https://s3-us-west-2.amazonaws.com/purplecarrot/corn-chowder-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/corn-chowder-full.jpg', 'The Purple Carrot headquarters is located right outside of Boston, so we’re big fans of Chowdah here! This recipe is a fresh take on classic corn chowder with a few original touches. First, fennel adds an herbaceous aroma to the mix. We also include watercress for a light crunch. Finally, turmeric gives the soup a dazzling golden hue, in addition to its anti-inflammatory properties. Health benefits and fine flavors make for a wicked good dinner!', 2, 830, 28, 131, 21);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Tofu Tikka Masala with Spring Vegetables & Brown Basmati Rice', 'https://s3-us-west-2.amazonaws.com/purplecarrot/tikka-masala-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/tikka-masala-full.jpg', 'If Tikka Masala is your go-to when it comes to Indian food, you’re in for a refreshing update on a classic recipe. The origins of this dish are unclear, but it is thought to have been created in Great Britain by a Bangladeshi chef. The sauce is what brings the distinctive tangy flavor, and can either be blended after simmering or left as is. Either way, bright tomato and creamy coconut milk deliver a rich base for a seriously satisfying dinner!', 2, 800, 42, 90, 28);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Tofu Banh Mi with Sunflower Seed Pate and Squash Pickles', 'https://s3-us-west-2.amazonaws.com/purplecarrot/banh-mi-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/banh-mi-full.jpg', 'Crispy tofu is a wonderful thing, and it’s extra special in this version because it’s baked instead of fried. Tips to help you get a great tofu: First, make sure your oven is up to temperature before you coat the tofu in the potato starch. Next, if you have a few extra moments, leave the tofu in the oven a bit longer. It will be an added crunch to this already delicious sandwich. Bread and butter squash pickles take it to the next level– this dish is sure to impress.', 2, 820, 28, 116, 26);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Wicked Healthy Chopped Salad with Charred Vegetables & Ginger-Miso Dressing', 'https://s3-us-west-2.amazonaws.com/purplecarrot/chopped-salad-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/chopped-salad-full.jpg', 'This summer recipe comes from our good friends at Wicked Healthy, a Boston based Chef duo that want you to eat your vegetables and have them taste great. It can be easily adapted for a grill, so heat one up before you begin and forgo the skillet in Step 4. The garbanzo beans get pan toasted and dusted with a smoked nori spice, black and white sesame seeds with nori and smoky spices. Serve this meal family style lightly drizzled with dressing.', 2, 520, 19, 71, 22);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Okonomiyaki with Vermicelli Noodle Salad & Sweet Shoyu', 'https://s3-us-west-2.amazonaws.com/purplecarrot/vermicelli-salad-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/vermicelli-salad-full.jpg', 'Okonomiyaki may be difficult to say (o-konomi-yaki) but they are simple to make and fun to eat. This Japanese pancake translates to “grilled how you like it” and gets a crispy, crunchy bottom when the mix hits a hot skillet. Adjust the heat as necessary and pick up the edge of the pancake to check for a golden browned bottom before you flip. For a finishing touch nori spice is sprinkled on top: seaweed, sesame seeds, and mild chile flakes.', 2, 710, 28, 104, 12);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Ancient Grain Bowl with Za’atar Roasted Cherry Tomatoes and Yogurt Cucumbers', 'https://s3-us-west-2.amazonaws.com/purplecarrot/grain-bowl-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/grain-bowl-full.jpg', 'Middle Eastern flavors meld in this simple yet hearty grain bowl. The fregola rustica shines with its blend of ancient grains, gourmet rice, and toasted pasta. Briney olives and crunchy walnuts top it all off along with za’atar roasted vegetables. Za’atar is an aromatic spice blend with tangy sumac, toasted sesame seeds, and dried thyme. It doesn’t contain salt so be sure to sprinkle your veggies with salt and pepper before you roast.', 2, 560, 29, 68, 15);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Agedashi Tofu with Sweet Miso Roasted Napa and Daikon Radish', 'https://s3-us-west-2.amazonaws.com/purplecarrot/agedashi-tofu-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/agedashi-tofu-full.jpg', 'Agedashi tofu is a well known dish, appearing in Japanese cookbooks as early as 1782. With a crisp crust and soft warm tofu inside, it hasn’t changed much over the years– and for good reason. The dish is actually shallow deep fried and can easily be done at home, with a quick flavorful broth and in this case, beautifully oven-browned napa cabbage. Get your oil nice and hot before placing the tofu in, it will avoid any excess oil getting absorbed.', 2, 930, 48, 101, 35);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Toasted Quinoa Stir-Fry with Crispy Sesame Shiitakes & Chinese Chives', 'https://s3-us-west-2.amazonaws.com/purplecarrot/quinoa-stirfry-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/quinoa-stirfry-full.jpg', 'In this toasty grain bowl, antioxidant-rich shiitakes are sautéed for a crunchy texture. You’ll notice that they absorb oil quickly; to keep this from happening too fast, make sure your pan is nice and hot before you start frying. This way you’ll end up with beautifully golden brown mushrooms! Enjoy them along with vivid watermelon radish and a garnish of chopped Chinese chives.', 2, 510, 19, 70, 19);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Better Bean Burger with Special Sauce & Classic Potato Salad', 'https://s3-us-west-2.amazonaws.com/purplecarrot/been-burger-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/been-burger-full.jpg', 'This 4th of July burger really has it all– a savory special sauce, melted American vegan cheese, and crisp, garlicky dill pickle chips. Sound familiar? It’s a classic revamped for the better. The red bliss potato salad gets its punch from celery, shallot, and mustard powder. Note: half of the pickles will be chopped and half are left in chips to serve alongside your burger.', 2, 1070, 58, 98, 32);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Portobello Mushroom BLT with Herb Mayo & Zesty Steak Fries', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mushroom-blt-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mushroom-blt-full.jpg', 'This sandwich is plant-based comfort food at its finest! Portobello mushrooms are marinated in maple syrup, liquid smoke, and spices to achieve a bacon-y flavor. Then, they’re pan-seared for added crispiness. Fresh herb mayo adds boldness, and a side of oven roasted steak fries completes the meal!', 2, 770, 39, 95, 17);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Loaded Sweet Potato Nachos with Avocado Salsa & Chipotle Crema', 'https://s3-us-west-2.amazonaws.com/purplecarrot/potato-nachos-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/potato-nachos-full.jpg', 'Did you know that the chipotle pepper is actually a vine-ripened jalapeño? It gets its powerful flavor from being dried over a smoky grill for several days. The crema that goes with these nachos is full of that fiery spice, while the avocado salsa brings the heat down a notch. With a black bean mash that packs in the protein, this dinner is far from your standard snack of chips and salsa!', 2, 790, 34, 126, 22);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Cauliflower Spare Ribs with Five-Spice BBQ Sauce & Ginger Fried Rice', 'https://s3-us-west-2.amazonaws.com/purplecarrot/spare-ribs-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/spare-ribs-full.jpg', 'The five spices in the seasoning blend used in this dish are star anise, cloves, Chinese cinnamon, Sichuan pepper, and fennel. This distinctive mixture gives the sauce a spicy, aromatic quality. Gingered black rice is reminiscent of your favorite takeout dish, and comes with the added bonus of savory glazed cauliflower “spare ribs” and a nutritious hemp seed garnish!', 2, 580, 22, 88, 18);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Herbed Barley Bowl with Buttery Mushrooms and Pickled Peppers', 'https://s3-us-west-2.amazonaws.com/purplecarrot/barley-bowl-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/barley-bowl-full.jpg', 'A blend of wild mushrooms over a bed of barley are the perfect pair. We’ll introduce you to a new cooking method, basting, which means adding moisture and texture by spooning sauce over your food while cooking. Have fun testing it out over these buttery mushrooms. The fresh parsley and mint add brightness while the pickled peppers bring a touch of sour. This dish will surely get you ready for spring!', 2, 670, 37, 78, 15);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'White BeanBall Sub with Arrabiata Sauce & Romaine Salad', 'https://s3-us-west-2.amazonaws.com/purplecarrot/beanball-sub-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/beanball-sub-full.jpg', 'Arrabiata means angry in Italian in reference to the spicy peppers it contains. Our version is made with tomatoes, garlic, and red chilis and is the perfect partner to the white bean “meatballs”. Baking the beanballs ensures they’re texture perfection - crispy on the outside and soft on the inside. A bright romaine salad and herby panko complete this filling and nutritious Italian meal!', 2, 780, 19, 107, 40);
-- INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
-- VALUES (13.27, 'Happy Pancake with Radish, Bok Choy & Pea Shoots', 'https://s3-us-west-2.amazonaws.com/purplecarrot/happy-pancake-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/happy-pancake-full.jpg', 'These Vietnamese happy pancakes have a chewy goodness that can’t be beat. Crisp vegetables, gingery spice, and a sweet tamari dressing represent everything we love about Southeast Asian cuisine! To ensure your pancake is fluffy, be sure to whisk your batter well before adding it to the pan.', 2, 410, 19, 54, 7);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Creamy Lentil Mushroom Stew with Kale', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mushroom-stew-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/mushroom-stew-full.jpg', 'Le Puy lentils are firm and have an earthy flavor, which is perfect for soups and stews! These unique characteristics are due to the terroir, or soil and climate, of the French region in which the lentils are grown. The optional addition of dry white wine adds an extra level of flavor to the dish. Make sure to give it enough time to reduce, and your stew will have an added layer of complexity.', 2, 810, 32, 104, 36);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Spicy Almond Butter Udon with Charred Brussels Sprouts', 'https://s3-us-west-2.amazonaws.com/purplecarrot/udon-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/udon-full.jpg', 'Bring on the udon! This Japanese inspired dish is full of nuts and veggies to make for a nutritious and filling dinner. The spicy almond butter sauce is truly a showstopper. Maple syrup cuts the heat from chili garlic paste, and with a touch of tamari, you’ll create a sweet and savory taste sensation. Pay extra attention to the use of water in Steps 2 though 4 to help you create that perfect sauce!', 2, 710, 35, 81, 28);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Quinoa Fried Rice with Tofu “Egg” and Edamame', 'https://s3-us-west-2.amazonaws.com/purplecarrot/fried-rice-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/fried-rice-full.jpg', 'Quinoa is a fiber-rich alternative to traditional fried rice, and it’s the perfect base in this dish! Additions include a rainbow of veggies, which add nutritional value as well as color. Another benefit that sets this dish apart from the beloved takeout staple is the tofu “egg”--compared to a real egg, this alternative is lower in fat, cholesterol, and calories.', 2, 640, 25, 74, 34);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Creamy Roasted Red Pepper Pasta with Asparagus & Pepita Parmesan', 'https://s3-us-west-2.amazonaws.com/purplecarrot/roasted-pasta-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/roasted-pasta-full.jpg', 'Enjoy your first taste of spring with this colorful meal. Crisp asparagus and roasted red pepper are tied together with a garden-inspired sauce that will have you looking forward to warmer times. The addition of tangy green olives offers a hint of acidity to balance out the rich flavors in this dish. And the pepita parmesan makes a cheesy topping that you’ll want to sprinkle on everything!', 2, 680, 27, 97, 14);
INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
VALUES (13.27, 'Red Posole with Chili de Arbol', 'https://s3-us-west-2.amazonaws.com/purplecarrot/posole-full.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/posole-full.jpg', 'Posole is a traditional Mexican soup that’s usually made with pork, garlic, hominy, and chilis. Our version is meat-free, but maintains the smoky spice that sets this dish apart! You’ll notice two unique flavors incorporated into this dish. The first is Mexican oregano, with hints of citrus and licorice that differentiate it from its Mediterranean cousin. The other is a blend of two different types of chiles to give your posole a serious kick!', 2, 640, 24, 81, 29);
-- INSERT INTO recipes (Price, Name, ImageFull, Thumbnail, Description, Servings, Calories, Fat, Carbs, Protein)
-- VALUES (13.27, '', 'https://s3-us-west-2.amazonaws.com/purplecarrot/.jpg', 'https://s3-us-west-2.amazonaws.com/purplecarrot/.jpg', '', 2, );



CREATE TABLE cart (
    id SERIAL PRIMARY KEY,
    recipesid INTEGER NOT NULL REFERENCES recipes(id),
    userid INTEGER NOT NULL REFERENCES users(id),
    quantity INTEGER,
    recipeThumbnail TEXT,
    name TEXT,
    price DECIMAL
);

INSERT INTO cart (recipesid, userid, quantity, recipeThumbnail, name, price)
VALUES (1, 1, 4, 'https://s3-us-west-2.amazonaws.com/purplecarrot/beet-burger-thumbnail.jpg', 'Beet Burger with Roasted Grapes & Herb Garlic Cashew Cheese', 13.27);
INSERT INTO cart (recipesid, userid, quantity, recipeThumbnail, name, price)
VALUES (2, 1, 2, 'https://s3-us-west-2.amazonaws.com/purplecarrot/maple-tempeh-thumbnail.jpg', 'Maple Tempeh with Lime Couscous Salad and Minty Plums', 13.27);
INSERT INTO cart (recipesid, userid, quantity, recipeThumbnail, name, price)
VALUES (3, 1, 3, 'https://s3-us-west-2.amazonaws.com/purplecarrot/tempeh-tacos-thumbnail.jpg', 'Tempeh Tacos Al Pastor with Pineapple Salsa', 13.27);
INSERT INTO cart (recipesid, userid, quantity, recipeThumbnail, name, price)
VALUES (4, 1, 4, 'https://s3-us-west-2.amazonaws.com/purplecarrot/kitchari-thumbnail.jpg', 'Wicked Healthy Kitchari with Minted Cucumber Avocado Salad & Toasted Naan', 13.27);
